default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "@Inspiron1"
  host: localhost

development:
  <<: *default
  database: db_ruby2d

